apiVersion: v1
kind: Service
metadata:
  name: nginx
  # service labels
  labels: 
    project: roboshop
    environmet: dev
spec:
  # service user the below labels to select the pods
  selector:
    project: roboshop
    tier: frontend
    component: frontend 
  ports:
    - protocol: TCP
      port: 80  # service port
      targetPort: 80 # container port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    project: roboshop
    environment: dev
    purpose: frontend
    tier: frontend
spec: 
  containers:
  - name: nginx #container name
    image: nginx #by default if will get from docker hub