apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  # service labels
  labels: 
    project: roboshop
    environmet: dev
spec:
  type: LoadBalancer
  # service user the below labels to select the pods
  selector:
    project: roboshop
    tier: frontend
    component: frontend 
  ports:
    - protocol: TCP
      port: 80  # service port
      targetPort: 80 # container port 
      nodePort: 30008
      
